[package]
name = "TP1"
version = "0.1.0"
edition = "2021"

[dependencies]
avr-device = { version = "0.6.0", features = ["atmega328p"] }
cortex-m-rt = "0.7.3"
cortex-m-semihosting = "0.5.0"
panic-halt = "0.2.0"

[profile.release]
panic = "abort"
