[package]
name = "TP1"
authors = ["David Mordi, Ines Kaci, Louis-Marie Matthews"]
version = "0.1.0"
edition = "2021"

[dependencies]
avr-device = { version = "0.6.0", features = ["atmega328p"] }
cortex-m-rt = "0.7.3"
cortex-m-semihosting = "0.5.0"
panic-halt = "0.2.0"

[profile.release]
panic = "abort"
codegen-units = 1 # Slower compilation, faster program
lto = true # Maximum linker optimisation
opt-level = "s" # Optimize code for smallest binary size

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"
